---
- hosts: automation
  become: yes
  tasks:
#  - name: "Server List"
#    ansible.builtin.ping:
#    register: ping_output
#
#  - name: "Ping Output"
#    debug:
#      msg: "{{ ping_output }}"
#  
#  - name: "Check Uptime"
#    ansible.builtin.command:
#      cmd: uptime 
#    register: uptime_output 
#
#  - name: "Uptime Output"
#    debug:
#      var: uptime_output.stdout 
#
  - name: Install Jenkins
    ansible.builtin.dnf:
      name:
        - java-11-openjdk 
        - java-11-openjdk-devel
      state: present

  - name: "Java Version"
    ansible.builtin.command:
      cmd: java --version
    register: java_check

  - name: "Java Version Check"
    debug:
      var: java_check.stdout
  
  - name: "Download Jenkins Repo and Install Key"
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
 
  - name: "Import Jenkins Key"
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key


  - name: "Install Jenkins Package"
    ansible.builtin.dnf:
      name: 
        - epel-release
        - jenkins
      state: latest
    register: package_installation

  - name: "Verify Package Installation"
    debug:
      var:  package_installation

  - name: "Start/Enable Jenkins Service and Verify"
    ansible.builtin.systemd:
      name: jenkins 
      state: started
      enabled: yes

  - name: "Verify if Jenkins service is started and enabled or not"
    ansible.builtin.command:
      cmd: systemctl status jenkins
    register: service_verification
    
  - name: "Systemctl Status Logs of Verification"   
    debug:
      var: service_verification

      
