---
- hosts: deployment_host
  tasks:
  - name: "List Openstack Images"
    shell: source ./admin-openrc.sh; openstack image list -c 'Name'
    register: image_list
    
  - name: "Delete Sanity Image and Recreate It"
    shell: source ./admin-openrc.sh; openstack image delete sanity-2
    when: "'sanity-2' in image_list.stdout"

  - name: "Create Openstack Sanity Image"
    shell: source ./admin-openrc.sh; openstack image create --container-format bare --disk-format raw --file /mnt/template/qcow2/cirros-0.6.1-aarch64-disk.raw sanity-2
    when: "'sanity-2' not in image_list.stdout"

  - name: "Wait until image is being uploaded"
    shell: source ./admin-openrc.sh;  openstack image show -c status -f value sanity-2
    register: image_upload_progress
    until: image_upload_progress.stdout is search("active")
    retries: 10
    delay: 10

  - name: "Justification for Task Failure"
    debug:
      msg: "Image sanity-2 is successfully uploaded"
    when: image_upload_progress.stdout is search("error")



