---
- hosts: deployment_host
  tasks:
  - name: "Authenitcate with Openstack Cloud Kolla Ansible"
    openstack.cloud.auth:
      cloud: kolla-admin

  - name: "Openstack Image Creation only if Image is not Present"
    openstack.cloud.image:
      cloud: kolla-admin
      name: sanity-1
      container_format: bare
      disk_format: raw
      filename: /mnt/template/qcow2/cirros-0.6.1-aarch64-disk.raw
    register: image_info

  - name: "Image Result"
    debug:
      msg: "{{ image_info.images:wq }}" 
